import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  const countriesData = [
    { name: "Antarctica", continent: "Antarctica" as const },
    { name: "Afghanistan", continent: "Asia" as const },
    { name: "Albania", continent: "Europe" as const },
    { name: "Algeria", continent: "Africa" as const },
    { name: "Andorra", continent: "Europe" as const },
    { name: "Angola", continent: "Africa" as const },
    { name: "Antigua and Barbuda", continent: "NorthAmerica" as const },
    { name: "Argentina", continent: "SouthAmerica" as const },
    { name: "Armenia", continent: "Asia" as const },
    { name: "Australia", continent: "Oceania" as const },
    { name: "Austria", continent: "Europe" as const },
    { name: "Azerbaijan", continent: "Asia" as const },
    { name: "Bahamas", continent: "NorthAmerica" as const },
    { name: "Bahrain", continent: "MiddleEast" as const },
    { name: "Bangladesh", continent: "Asia" as const },
    { name: "Barbados", continent: "NorthAmerica" as const },
    { name: "Belarus", continent: "Europe" as const },
    { name: "Belgium", continent: "Europe" as const },
    { name: "Belize", continent: "NorthAmerica" as const },
    { name: "Benin", continent: "Africa" as const },
    { name: "Bhutan", continent: "Asia" as const },
    { name: "Bolivia", continent: "SouthAmerica" as const },
    { name: "Bosnia and Herzegovina", continent: "Europe" as const },
    { name: "Botswana", continent: "Africa" as const },
    { name: "Brazil", continent: "SouthAmerica" as const },
    { name: "Brunei", continent: "Asia" as const },
    { name: "Bulgaria", continent: "Europe" as const },
    { name: "Burkina Faso", continent: "Africa" as const },
    { name: "Burundi", continent: "Africa" as const },
    { name: "Cabo Verde", continent: "Africa" as const },
    { name: "Cambodia", continent: "Asia" as const },
    { name: "Cameroon", continent: "Africa" as const },
    { name: "Canada", continent: "NorthAmerica" as const },
    { name: "Central African Republic", continent: "Africa" as const },
    { name: "Chad", continent: "Africa" as const },
    { name: "Chile", continent: "SouthAmerica" as const },
    { name: "China", continent: "Asia" as const },
    { name: "Colombia", continent: "SouthAmerica" as const },
    { name: "Comoros", continent: "Africa" as const },
    { name: "Congo", continent: "Africa" as const },
    { name: "Costa Rica", continent: "NorthAmerica" as const },
    { name: "Croatia", continent: "Europe" as const },
    { name: "Cuba", continent: "NorthAmerica" as const },
    { name: "Cyprus", continent: "Europe" as const },
    { name: "Czech Republic", continent: "Europe" as const },
    { name: "Democratic Republic of the Congo", continent: "Africa" as const },
    { name: "Denmark", continent: "Europe" as const },
    { name: "Djibouti", continent: "Africa" as const },
    { name: "Dominica", continent: "NorthAmerica" as const },
    { name: "Dominican Republic", continent: "NorthAmerica" as const },
    { name: "Ecuador", continent: "SouthAmerica" as const },
    { name: "Egypt", continent: "Africa" as const },
    { name: "El Salvador", continent: "NorthAmerica" as const },
    { name: "Equatorial Guinea", continent: "Africa" as const },
    { name: "Eritrea", continent: "Africa" as const },
    { name: "Estonia", continent: "Europe" as const },
    { name: "Eswatini", continent: "Africa" as const },
    { name: "Ethiopia", continent: "Africa" as const },
    { name: "Fiji", continent: "Oceania" as const },
    { name: "Finland", continent: "Europe" as const },
    { name: "France", continent: "Europe" as const },
    { name: "Gabon", continent: "Africa" as const },
    { name: "Gambia", continent: "Africa" as const },
    { name: "Georgia", continent: "Asia" as const },
    { name: "Germany", continent: "Europe" as const },
    { name: "Ghana", continent: "Africa" as const },
    { name: "Greece", continent: "Europe" as const },
    { name: "Grenada", continent: "NorthAmerica" as const },
    { name: "Guatemala", continent: "NorthAmerica" as const },
    { name: "Guinea", continent: "Africa" as const },
    { name: "Guinea-Bissau", continent: "Africa" as const },
    { name: "Guyana", continent: "SouthAmerica" as const },
    { name: "Haiti", continent: "NorthAmerica" as const },
    { name: "Holy See", continent: "Europe" as const },
    { name: "Honduras", continent: "NorthAmerica" as const },
    { name: "Hungary", continent: "Europe" as const },
    { name: "Iceland", continent: "Europe" as const },
    { name: "India", continent: "Asia" as const },
    { name: "Indonesia", continent: "Asia" as const },
    { name: "Iran", continent: "MiddleEast" as const },
    { name: "Iraq", continent: "MiddleEast" as const },
    { name: "Ireland", continent: "Europe" as const },
    { name: "Israel", continent: "MiddleEast" as const },
    { name: "Italy", continent: "Europe" as const },
    { name: "Jamaica", continent: "NorthAmerica" as const },
    { name: "Japan", continent: "Asia" as const },
    { name: "Jordan", continent: "MiddleEast" as const },
    { name: "Kazakhstan", continent: "Asia" as const },
    { name: "Kenya", continent: "Africa" as const },
    { name: "Kiribati", continent: "Oceania" as const },
    { name: "Kuwait", continent: "MiddleEast" as const },
    { name: "Kyrgyzstan", continent: "Asia" as const },
    { name: "Laos", continent: "Asia" as const },
    { name: "Latvia", continent: "Europe" as const },
    { name: "Lebanon", continent: "MiddleEast" as const },
    { name: "Lesotho", continent: "Africa" as const },
    { name: "Liberia", continent: "Africa" as const },
    { name: "Libya", continent: "Africa" as const },
    { name: "Liechtenstein", continent: "Europe" as const },
    { name: "Lithuania", continent: "Europe" as const },
    { name: "Luxembourg", continent: "Europe" as const },
    { name: "Madagascar", continent: "Africa" as const },
    { name: "Malawi", continent: "Africa" as const },
    { name: "Malaysia", continent: "Asia" as const },
    { name: "Maldives", continent: "Asia" as const },
    { name: "Mali", continent: "Africa" as const },
    { name: "Malta", continent: "Europe" as const },
    { name: "Marshall Islands", continent: "Oceania" as const },
    { name: "Mauritania", continent: "Africa" as const },
    { name: "Mauritius", continent: "Africa" as const },
    { name: "Mexico", continent: "NorthAmerica" as const },
    { name: "Micronesia", continent: "Oceania" as const },
    { name: "Moldova", continent: "Europe" as const },
    { name: "Monaco", continent: "Europe" as const },
    { name: "Mongolia", continent: "Asia" as const },
    { name: "Montenegro", continent: "Europe" as const },
    { name: "Morocco", continent: "Africa" as const },
    { name: "Mozambique", continent: "Africa" as const },
    { name: "Myanmar", continent: "Asia" as const },
    { name: "Namibia", continent: "Africa" as const },
    { name: "Nauru", continent: "Oceania" as const },
    { name: "Nepal", continent: "Asia" as const },
    { name: "Netherlands", continent: "Europe" as const },
    { name: "New Zealand", continent: "Oceania" as const },
    { name: "Nicaragua", continent: "NorthAmerica" as const },
    { name: "Niger", continent: "Africa" as const },
    { name: "Nigeria", continent: "Africa" as const },
    { name: "North Korea", continent: "Asia" as const },
    { name: "North Macedonia", continent: "Europe" as const },
    { name: "Norway", continent: "Europe" as const },
    { name: "Oman", continent: "MiddleEast" as const },
    { name: "Pakistan", continent: "Asia" as const },
    { name: "Palau", continent: "Oceania" as const },
    { name: "Palestine State", continent: "MiddleEast" as const },
    { name: "Panama", continent: "NorthAmerica" as const },
    { name: "Papua New Guinea", continent: "Oceania" as const },
    { name: "Paraguay", continent: "SouthAmerica" as const },
    { name: "Peru", continent: "SouthAmerica" as const },
    { name: "Philippines", continent: "Asia" as const },
    { name: "Poland", continent: "Europe" as const },
    { name: "Portugal", continent: "Europe" as const },
    { name: "Qatar", continent: "MiddleEast" as const },
    { name: "Romania", continent: "Europe" as const },
    { name: "Russia", continent: "Europe" as const },
    { name: "Rwanda", continent: "Africa" as const },
    { name: "Saint Kitts and Nevis", continent: "NorthAmerica" as const },
    { name: "Saint Lucia", continent: "NorthAmerica" as const },
    {
      name: "Saint Vincent and the Grenadines",
      continent: "NorthAmerica" as const,
    },
    { name: "Samoa", continent: "Oceania" as const },
    { name: "San Marino", continent: "Europe" as const },
    { name: "Sao Tome and Principe", continent: "Africa" as const },
    { name: "Saudi Arabia", continent: "MiddleEast" as const },
    { name: "Senegal", continent: "Africa" as const },
    { name: "Serbia", continent: "Europe" as const },
    { name: "Seychelles", continent: "Africa" as const },
    { name: "Sierra Leone", continent: "Africa" as const },
    { name: "Singapore", continent: "Asia" as const },
    { name: "Slovakia", continent: "Europe" as const },
    { name: "Slovenia", continent: "Europe" as const },
    { name: "Solomon Islands", continent: "Oceania" as const },
    { name: "Somalia", continent: "Africa" as const },
    { name: "South Africa", continent: "Africa" as const },
    { name: "South Korea", continent: "Asia" as const },
    { name: "South Sudan", continent: "Africa" as const },
    { name: "Spain", continent: "Europe" as const },
    { name: "Sri Lanka", continent: "Asia" as const },
    { name: "Sudan", continent: "Africa" as const },
    { name: "Suriname", continent: "SouthAmerica" as const },
    { name: "Sweden", continent: "Europe" as const },
    { name: "Switzerland", continent: "Europe" as const },
    { name: "Syria", continent: "MiddleEast" as const },
    { name: "Tajikistan", continent: "Asia" as const },
    { name: "Tanzania", continent: "Africa" as const },
    { name: "Thailand", continent: "Asia" as const },
    { name: "Timor-Leste", continent: "Asia" as const },
    { name: "Togo", continent: "Africa" as const },
    { name: "Tonga", continent: "Oceania" as const },
    { name: "Trinidad and Tobago", continent: "NorthAmerica" as const },
    { name: "Tunisia", continent: "Africa" as const },
    { name: "Turkey", continent: "MiddleEast" as const },
    { name: "Turkmenistan", continent: "Asia" as const },
    { name: "Tuvalu", continent: "Oceania" as const },
    { name: "Uganda", continent: "Africa" as const },
    { name: "Ukraine", continent: "Europe" as const },
    { name: "United Arab Emirates", continent: "MiddleEast" as const },
    { name: "United Kingdom", continent: "Europe" as const },
    { name: "United States of America", continent: "NorthAmerica" as const },
    { name: "Uruguay", continent: "SouthAmerica" as const },
    { name: "Uzbekistan", continent: "Asia" as const },
    { name: "Vanuatu", continent: "Oceania" as const },
    { name: "Venezuela", continent: "SouthAmerica" as const },
    { name: "Vietnam", continent: "Asia" as const },
    { name: "Yemen", continent: "MiddleEast" as const },
    { name: "Zambia", continent: "Africa" as const },
    { name: "Zimbabwe", continent: "Africa" as const },
    { name: "Global", continent: "Global" as const },
    { name: "Middle East", continent: "MiddleEast" as const },
    { name: "Europe", continent: "Europe" as const },
    { name: "South America", continent: "Global" as const },
    { name: "Oceania", continent: "Oceania" as const },
    { name: "North America", continent: "NorthAmerica" as const },
    { name: "Africa", continent: "Africa" as const },
    { name: "Asia", continent: "Asia" as const },
  ];

  await prisma.country.createMany({
    data: countriesData,
    skipDuplicates: true,
  });

  const populationData = [
    { yearStart: -300_000, yearEnd: -200_001, population: 10_000 },
    { yearStart: -200_000, yearEnd: -100_001, population: 50_000 },
    { yearStart: -100_000, yearEnd: -50_001, population: 100_000 },
    { yearStart: -50_000, yearEnd: -10_001, population: 500_000 },
    { yearStart: -10_000, yearEnd: -9_001, population: 2_000_000 },
    { yearStart: -9_000, yearEnd: -5_001, population: 4_000_000 },
    { yearStart: -5_000, yearEnd: -4_001, population: 5_000_000 },
    { yearStart: -4_000, yearEnd: -3_001, population: 7_000_000 },
    { yearStart: -3_000, yearEnd: -2_001, population: 14_000_000 },
    { yearStart: -2_000, yearEnd: -1_001, population: 27_000_000 },
    { yearStart: -1_000, yearEnd: -501, population: 50_000_000 },
    { yearStart: -500, yearEnd: -201, population: 100_000_000 },
    { yearStart: -200, yearEnd: 300, population: 150_000_000 },
    { yearStart: 201, yearEnd: 600, population: 190_000_000 },
    { yearStart: 601, yearEnd: 700, population: 200_000_000 },
    { yearStart: 701, yearEnd: 800, population: 210_000_000 },
    { yearStart: 801, yearEnd: 900, population: 220_000_000 },
    { yearStart: 901, yearEnd: 1000, population: 240_000_000 },
    { yearStart: 1001, yearEnd: 1100, population: 275_000_000 },
    { yearStart: 1101, yearEnd: 1200, population: 320_000_000 },
    { yearStart: 1201, yearEnd: 1400, population: 360_000_000 },
    { yearStart: 1401, yearEnd: 1500, population: 350_000_000 },
    { yearStart: 1501, yearEnd: 1600, population: 450_000_000 },
    { yearStart: 1601, yearEnd: 1700, population: 500_000_000 },
    { yearStart: 1701, yearEnd: 1759, population: 610_000_000 },
    { yearStart: 1760, yearEnd: 1803, population: 770_000_000 },
    { yearStart: 1804, yearEnd: 1849, population: 1_000_000_000 },
    { yearStart: 1850, yearEnd: 1899, population: 1_200_000_000 },
    { yearStart: 1900, yearEnd: 1919, population: 1_650_000_000 },
    { yearStart: 1920, yearEnd: 1939, population: 2_000_000_000 },
    { yearStart: 1940, yearEnd: 1959, population: 2_500_000_000 },
    { yearStart: 1960, yearEnd: 1979, population: 3_500_000_000 },
    { yearStart: 1980, yearEnd: 1989, population: 4_500_000_000 },
    { yearStart: 1990, yearEnd: 1999, population: 5_300_000_000 },
    { yearStart: 2000, yearEnd: 2009, population: 6_100_000_000 },
    { yearStart: 2010, yearEnd: 2019, population: 7_000_000_000 },
    { yearStart: 2020, yearEnd: 2025, population: 8_230_000_000 },
  ];

  await prisma.population.createMany({
    data: populationData,
    skipDuplicates: true,
  });

  const subjectsData = [
    { name: "military" },
    { name: "politics" },
    { name: "culture" },
    { name: "intellectual" },
    { name: "environment" },
    { name: "maritime" },
    { name: "religion" },
    { name: "economic" },
    { name: "art" },
    { name: "music" },
    { name: "science" },
  ];

  await prisma.subject.createMany({
    data: subjectsData,
    skipDuplicates: true,
  });

  console.log("Seed finished!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
