// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/timeline": {
    params: {};
  };
  "/timeline/:groupSlug": {
    params: {
      "groupSlug": string;
    };
  };
  "/register": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/forgot-password": {
    params: {};
  };
  "/reset-password": {
    params: {};
  };
  "/verify": {
    params: {};
  };
  "/user/:id": {
    params: {
      "id": string;
    };
  };
  "/articles": {
    params: {};
  };
  "/articles/create": {
    params: {};
  };
  "/articles/edit/:id": {
    params: {
      "id": string;
    };
  };
  "/review-suggestions": {
    params: {};
  };
  "/terms": {
    params: {};
  };
  "/privacy": {
    params: {};
  };
  "/cookies": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/timeline" | "/timeline/:groupSlug" | "/register" | "/login" | "/forgot-password" | "/reset-password" | "/verify" | "/user/:id" | "/articles" | "/articles/create" | "/articles/edit/:id" | "/review-suggestions" | "/terms" | "/privacy" | "/cookies" | "/*";
  };
  "./routes/app-layout.tsx": {
    id: "routes/app-layout";
    page: "/" | "/timeline" | "/timeline/:groupSlug" | "/register" | "/login" | "/forgot-password" | "/reset-password" | "/verify" | "/user/:id" | "/articles" | "/articles/create" | "/articles/edit/:id" | "/review-suggestions" | "/terms" | "/privacy" | "/cookies" | "/*";
  };
  "./routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "./routes/timeline.tsx": {
    id: "routes/timeline";
    page: "/timeline" | "/timeline/:groupSlug";
  };
  "./routes/timeline.index.tsx": {
    id: "routes/timeline.index";
    page: "/timeline";
  };
  "./routes/timeline.$groupSlug.tsx": {
    id: "routes/timeline.$groupSlug";
    page: "/timeline/:groupSlug";
  };
  "./routes/register.tsx": {
    id: "routes/register";
    page: "/register";
  };
  "./routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "./routes/forgot-password.tsx": {
    id: "routes/forgot-password";
    page: "/forgot-password";
  };
  "./routes/reset-password.tsx": {
    id: "routes/reset-password";
    page: "/reset-password";
  };
  "./routes/verify.tsx": {
    id: "routes/verify";
    page: "/verify";
  };
  "./routes/user.$id.tsx": {
    id: "routes/user.$id";
    page: "/user/:id";
  };
  "./routes/articles.tsx": {
    id: "routes/articles";
    page: "/articles" | "/articles/create" | "/articles/edit/:id";
  };
  "./routes/articles.create.tsx": {
    id: "routes/articles.create";
    page: "/articles/create";
  };
  "./routes/articles.edit.$id.tsx": {
    id: "routes/articles.edit.$id";
    page: "/articles/edit/:id";
  };
  "./routes/review-suggestions.tsx": {
    id: "routes/review-suggestions";
    page: "/review-suggestions";
  };
  "./routes/terms.tsx": {
    id: "routes/terms";
    page: "/terms";
  };
  "./routes/privacy.tsx": {
    id: "routes/privacy";
    page: "/privacy";
  };
  "./routes/cookies.tsx": {
    id: "routes/cookies";
    page: "/cookies";
  };
  "./routes/not-found.tsx": {
    id: "routes/not-found";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/app-layout": typeof import("./app/./routes/app-layout.tsx");
  "routes/home": typeof import("./app/./routes/home.tsx");
  "routes/timeline": typeof import("./app/./routes/timeline.tsx");
  "routes/timeline.index": typeof import("./app/./routes/timeline.index.tsx");
  "routes/timeline.$groupSlug": typeof import("./app/./routes/timeline.$groupSlug.tsx");
  "routes/register": typeof import("./app/./routes/register.tsx");
  "routes/login": typeof import("./app/./routes/login.tsx");
  "routes/forgot-password": typeof import("./app/./routes/forgot-password.tsx");
  "routes/reset-password": typeof import("./app/./routes/reset-password.tsx");
  "routes/verify": typeof import("./app/./routes/verify.tsx");
  "routes/user.$id": typeof import("./app/./routes/user.$id.tsx");
  "routes/articles": typeof import("./app/./routes/articles.tsx");
  "routes/articles.create": typeof import("./app/./routes/articles.create.tsx");
  "routes/articles.edit.$id": typeof import("./app/./routes/articles.edit.$id.tsx");
  "routes/review-suggestions": typeof import("./app/./routes/review-suggestions.tsx");
  "routes/terms": typeof import("./app/./routes/terms.tsx");
  "routes/privacy": typeof import("./app/./routes/privacy.tsx");
  "routes/cookies": typeof import("./app/./routes/cookies.tsx");
  "routes/not-found": typeof import("./app/./routes/not-found.tsx");
};