const COUNTRY_MAP: Record<string, string> = {
  USA: "United States of America",
  "U.S.A.": "United States of America",
  US: "United States of America",
  "United States": "United States of America",
  America: "United States of America",
  UK: "United Kingdom",
  "U.K.": "United Kingdom",
  England: "United Kingdom",
  Wales: "United Kingdom",
  Scotland: "United Kingdom",
  "Great Britain": "United Kingdom",
  "Ivory Coast": "Côte d'Ivoire",
  Czechia: "Czech Republic",
  DRC: "Democratic Republic of the Congo",
  "Republic of Congo": "Congo",
  Vatican: "Holy See",
  Palestine: "Palestine State",
  "East Timor": "Timor-Leste",
  "Russian Federation": "Russia",
  "Iran, Islamic Republic of": "Iran",
  "Syria Arab Republic": "Syria",
  "Viet Nam": "Vietnam",
  "Lao People's Democratic Republic": "Laos",
  Macedonia: "North Macedonia",
  "Republic of Macedonia": "North Macedonia",
  "Republic of China": "Taiwan",
  "Congo-Brazzaville": "Congo",
  "Bolivia (Plurinational State of)": "Bolivia",
  "Tanzania, United Republic of": "Tanzania",
  "Venezuela, Bolivarian Republic of": "Venezuela",
  "Egypt, Arab Republic of": "Egypt",
  "Federated States of Micronesia": "Micronesia",
  "Brunei Darussalam": "Brunei",
  UKRAINE: "Ukraine",
  "Republic of South Sudan": "South Sudan",
  "Republic of Ireland": "Ireland",
  "Republic of Moldova": "Moldova",
  "Cape Verde": "Cabo Verde",
  Burma: "Myanmar",
  "Saint Kitts": "Saint Kitts and Nevis",
  "Saint Vincent and the Grenadines": "Saint Vincent",
  "Persia": "Iran",
  "Rome": "Italy",
};

export function normaliseCountryName(name: string): string {
  const trimmed = name.trim();
  return COUNTRY_MAP[trimmed] || trimmed;
}
