export const collapseData = [
  {
    title: "Type",
    options: [
      { value: "person", labelText: "People", name: "type" },
      { value: "landmark", labelText: "Landmark", name: "type" },
      { value: "event", labelText: "Event", name: "type" },
      { value: "period", labelText: "Period", name: "type" },
    ],
  },
  {
    title: "Subject",
    options: [
      { value: "military", labelText: "Military", name: "subject" },
      { value: "politics", labelText: "Politics", name: "subject" },
      { value: "culture", labelText: "Culture", name: "subject" },
      { value: "intellectual", labelText: "Intellectual", name: "subject" },
      { value: "art", labelText: "Art", name: "subject" },
      { value: "maritime", labelText: "Maritime", name: "subject" },
      { value: "religion", labelText: "Religion", name: "subject" },
      { value: "environment", labelText: "Environment", name: "subject" },
      { value: "economic", labelText: "Economic", name: "subject" },
    ],
  },
  {
    title: "Continent",
    options: [
      { value: "Asia", labelText: "Asia", name: "continent" },
      { value: "Africa", labelText: "Africa", name: "continent" },
      { value: "Antarctica", labelText: "Antarctica", name: "continent" },
      { value: "Europe", labelText: "Europe", name: "continent" },
      { value: "MiddleEast", labelText: "Middle East", name: "continent" },
      { value: "NorthAmerica", labelText: "North America", name: "continent" },
      { value: "Oceania", labelText: "Oceania", name: "continent" },
      { value: "SouthAmerica", labelText: "South America", name: "continent" },
    ],
  },
];

export const themes = {
  title: "Theme",
  options: [
    { value: 5, slug: "ancient-china", labelText: "Ancient China", name: "group" },
    { value: 1, slug: "ancient-egypt", labelText: "Ancient Egypt", name: "group" },
    { value: 2, slug: "ancient-greece", labelText: "Ancient Greece", name: "group" },
    { value: 20, slug: "ancient-india", labelText: "Ancient India", name: "group" },
    { value: 3, slug: "ancient-rome", labelText: "Ancient Rome", name: "group" },
    { value: 19, slug: "andean-civilizations", labelText: "Andean Civilizations", name: "group" },
    { value: 24, slug: "baroque", labelText: "Baroque", name: "group" },
    { value: 41, slug: "black-history", labelText: "Black History", name: "group" },
    { value: 12, slug: "byzantine-empire", labelText: "Byzantine Empire", name: "group" },
    { value: 26, slug: "classical-japan", labelText: "Classical Japan", name: "group" },
    { value: 39, slug: "cold-war", labelText: "Cold War", name: "group" },
    { value: 30, slug: "colonial-brazil", labelText: "Colonial and Imperial Brazil", name: "group" },
    { value: 45, slug: "colonial-north-america", labelText: "Colonial North America", name: "group" },
    { value: 37, slug: "colonial-southeast-asia", labelText: "Colonial Southeast Asia", name: "group" },
    { value: 29, slug: "colonial-spanish-america", labelText: "Colonial Spanish America", name: "group" },
    { value: 23, slug: "early-islamic-period", labelText: "Early Islamic Period", name: "group" },
    { value: 35, slug: "early-modern-europe", labelText: "Early Modern Europe", name: "group" },
    { value: 46, slug: "early-republic", labelText: "Early Republic", name: "group" },
    { value: 42, slug: "feminism", labelText: "Feminism", name: "group" },
    { value: 27, slug: "feudal-japan", labelText: "Feudal Japan", name: "group" },
    { value: 47, slug: "gilded-age", labelText: "Gilded Age", name: "group" },
    { value: 40, slug: "globalization", labelText: "Globalization", name: "group" },
    { value: 22, slug: "imperial-china", labelText: "Imperial China", name: "group" },
    { value: 14, slug: "industrial-revolution", labelText: "Industrial Revolution", name: "group" },
    { value: 8, slug: "islamic-golden-age", labelText: "Islamic Golden Age", name: "group" },
    { value: 6, slug: "medieval-europe", labelText: "Medieval Europe", name: "group" },
    { value: 18, slug: "mesoamerica", labelText: "Mesoamerica", name: "group" },
    { value: 4, slug: "mesopotamia", labelText: "Mesopotamia", name: "group" },
    { value: 48, slug: "modern-china", labelText: "Modern China", name: "group" },
    { value: 15, slug: "modern-era", labelText: "Modern Era", name: "group" },
    { value: 28, slug: "modern-japan", labelText: "Modern Japan", name: "group" },
    { value: 11, slug: "mongol-empire", labelText: "Mongol Empire", name: "group" },
    { value: 16, slug: "ottoman-empire", labelText: "Ottoman Empire", name: "group" },
    { value: 21, slug: "persian-empire", labelText: "Persian Empire", name: "group" },
    { value: 25, slug: "pirates", labelText: "Pirates", name: "group" },
    { value: 34, slug: "polynesia-oceania", labelText: "Polynesia and Oceania", name: "group" },
    { value: 44, slug: "post-independence-south-america", labelText: "Post-Independence South America", name: "group" },
    { value: 43, slug: "pre-columbian-brazil", labelText: "Pre-Columbian Brazil", name: "group" },
    { value: 10, slug: "precolonial-north-america", labelText: "Precolonial North America", name: "group" },
    { value: 31, slug: "precolonial-southeast-asia", labelText: "Precolonial Southeast Asia", name: "group" },
    { value: 49, slug: "prehistory", labelText: "Prehistory", name: "group" },
    { value: 36, slug: "reformation-religious-wars", labelText: "Reformation and Religious Wars", name: "group" },
    { value: 7, slug: "renaissance", labelText: "Renaissance", name: "group" },
    { value: 33, slug: "silk-road", labelText: "Silk Road", name: "group" },
    { value: 17, slug: "sub-saharan-kingdoms", labelText: "Sub-Saharan Kingdoms", name: "group" },
    { value: 38, slug: "enlightenment", labelText: "The Enlightenment", name: "group" },
    { value: 9, slug: "viking-age", labelText: "Viking Age", name: "group" },
    { value: 32, slug: "west-african-empires", labelText: "West African Empires", name: "group" },
    { value: 50, slug: "wwii", labelText: "WWII", name: "group" },
  ],
} as const;