export const collapseData = [
  {
    title: "Type",
    options: [
      { value: "person", labelText: "People", name: "type" },
      { value: "landmark", labelText: "Landmark", name: "type" },
      { value: "event", labelText: "Event", name: "type" },
      { value: "period", labelText: "Period", name: "type" },
    ],
  },
  {
    title: "Subject",
    options: [
      { value: "military", labelText: "Military", name: "subject" },
      { value: "politics", labelText: "Politics", name: "subject" },
      { value: "culture", labelText: "Culture", name: "subject" },
      { value: "intellectual", labelText: "Intellectual", name: "subject" },
      { value: "art", labelText: "Art", name: "subject" },
      { value: "maritime", labelText: "Maritime", name: "subject" },
      { value: "religion", labelText: "Religion", name: "subject" },
      { value: "environment", labelText: "Environment", name: "subject" },
      { value: "economic", labelText: "Economic", name: "subject" },
    ],
  },
  {
    title: "Continent",
    options: [
      { value: "Asia", labelText: "Asia", name: "continent" },
      { value: "Africa", labelText: "Africa", name: "continent" },
      { value: "Antarctica", labelText: "Antarctica", name: "continent" },
      { value: "Europe", labelText: "Europe", name: "continent" },
      { value: "MiddleEast", labelText: "Middle East", name: "continent" },
      { value: "NorthAmerica", labelText: "North America", name: "continent" },
      { value: "Oceania", labelText: "Oceania", name: "continent" },
      { value: "SouthAmerica", labelText: "South America", name: "continent" },
    ],
  },
];

export const themes = {
  title: "Theme",
  options: [
    { value: 5, labelText: "Ancient China", name: "group" },
    { value: 1, labelText: "Ancient Egypt", name: "group" },
    { value: 2, labelText: "Ancient Greece", name: "group" },
    { value: 20, labelText: "Ancient India", name: "group" },
    { value: 3, labelText: "Ancient Rome", name: "group" },
    { value: 19, labelText: "Andean Civilizations", name: "group" },
    { value: 24, labelText: "Baroque", name: "group" },
    { value: 41, labelText: "Black History", name: "group" },
    { value: 12, labelText: "Byzantine Empire", name: "group" },
    { value: 26, labelText: "Classical Japan", name: "group" },
    { value: 39, labelText: "Cold War", name: "group" },
    { value: 30, labelText: "Colonial and Imperial Brazil", name: "group" },
    { value: 45, labelText: "Colonial North America", name: "group" },
    { value: 37, labelText: "Colonial Southeast Asia", name: "group" },
    { value: 29, labelText: "Colonial Spanish America", name: "group" },
    { value: 23, labelText: "Early Islamic Period", name: "group" },
    { value: 35, labelText: "Early Modern Europe", name: "group" },
    { value: 46, labelText: "Early Republic", name: "group" },
    { value: 42, labelText: "Feminism", name: "group" },
    { value: 27, labelText: "Feudal Japan", name: "group" },
    { value: 47, labelText: "Gilded Age", name: "group" },
    { value: 40, labelText: "Globalization", name: "group" },
    { value: 22, labelText: "Imperial China", name: "group" },
    { value: 14, labelText: "Industrial Revolution", name: "group" },
    { value: 8, labelText: "Islamic Golden Age", name: "group" },
    { value: 6, labelText: "Medieval Europe", name: "group" },
    { value: 18, labelText: "Mesoamerica", name: "group" },
    { value: 4, labelText: "Mesopotamia", name: "group" },
    { value: 48, labelText: "Modern China", name: "group" },
    { value: 15, labelText: "Modern Era", name: "group" },
    { value: 28, labelText: "Modern Japan", name: "group" },
    { value: 11, labelText: "Mongol Empire", name: "group" },
    { value: 16, labelText: "Ottoman Empire", name: "group" },
    { value: 21, labelText: "Persian Empire", name: "group" },
    { value: 25, labelText: "Pirates", name: "group" },
    { value: 34, labelText: "Polynesia and Oceania", name: "group" },
    { value: 44, labelText: "Post-Independence South America", name: "group" },
    { value: 43, labelText: "Pre-Columbian Brazil", name: "group" },
    { value: 10, labelText: "Precolonial North America", name: "group" },
    { value: 31, labelText: "Precolonial Southeast Asia", name: "group" },
    { value: 49, labelText: "Prehistory", name: "group" },
    { value: 36, labelText: "Reformation and Religious Wars", name: "group" },
    { value: 7, labelText: "Renaissance", name: "group" },
    { value: 33, labelText: "Silk Road", name: "group" },
    { value: 17, labelText: "Sub-Saharan Kingdoms", name: "group" },
    { value: 38, labelText: "The Enlightenment", name: "group" },
    { value: 9, labelText: "Viking Age", name: "group" },
    { value: 32, labelText: "West African Empires", name: "group" },
    { value: 50, labelText: "WWII", name: "group" },
  ],
};
