import {
  GiStoneAxe,
  GiWheat,
  GiScrollUnfurled,
  GiAxeSword,
  GiGreekSphinx,
  GiTempleGate,
  GiCastle,
  GiCompass,
  GiFactory,
  GiFallingBomb,
  GiSubmarineMissile,
  GiCaveman,
  GiAnvil,
  GiEgyptianPyramids,
  GiLaurelCrown,
  GiVisoredHelm,
  GiQuillInk,
  GiPalette,
  GiPalmTree,
  GiCaveEntrance,
  GiWireframeGlobe,
  GiMountains,
  GiFootprint,
  GiDiploma,
  GiFlame,
  GiMountainRoad,
  GiCrown,
  GiShipWheel,
} from "react-icons/gi";

import type { IconType } from "react-icons";

export interface HistoricalRange {
  label: string;
  start: number;
  end: number;
  icon: IconType;
  headline: string;
}

export const HISTORICAL_RANGES: HistoricalRange[] = [
  // Prehistory & Early Civilizations
  {
    label: "Paleolithic Era",
    start: -300000,
    end: -10000,
    icon: GiCaveEntrance,
    headline: "Origins of Humanity and the Stone Age",
  },
  {
    label: "Mesolithic Era",
    start: -10000,
    end: -5000,
    icon: GiCaveman,
    headline: "Transitional Hunter‑Gatherers",
  },
  {
    label: "Neolithic Revolution",
    start: -5000,
    end: -3000,
    icon: GiStoneAxe,
    headline: "Spread of Farming and Early Villages",
  },

  // Bronze Age
  {
    label: "Early Bronze Age",
    start: -3000,
    end: -2000,
    icon: GiAnvil,
    headline: "Metalwork and Monarchy",
  },
  {
    label: "Middle Bronze Age",
    start: -2000,
    end: -1500,
    icon: GiEgyptianPyramids,
    headline: "Empires Forge Ahead",
  },
  {
    label: "Late Bronze Age",
    start: -1500,
    end: -1200,
    icon: GiFallingBomb,
    headline: "Civilizations in Turmoil",
  },

  // Iron Age & Classical
  {
    label: "Iron Age",
    start: -1200,
    end: -500,
    icon: GiAxeSword,
    headline: "Tools of Power",
  },
  {
    label: "Classical Antiquity",
    start: -500,
    end: 300,
    icon: GiLaurelCrown,
    headline: "Rise of the Roman Empire",
  },
  {
    label: "Late Antiquity",
    start: 300,
    end: 500,
    icon: GiTempleGate,
    headline: "The Twilight of Empires",
  },
  // Medieval
  {
    label: "Early Middle Ages",
    start: 500,
    end: 1000,
    icon: GiVisoredHelm,
    headline: "Kings and Conquests",
  },
  {
    label: "High Middle Ages",
    start: 1000,
    end: 1300,
    icon: GiCastle,
    headline: "Castles and Crusades",
  },
  {
    label: "Late Middle Ages",
    start: 1300,
    end: 1500,
    icon: GiCastle,
    headline: "Plague and War",
  },

  // Renaissance → Early Modern
  {
    label: "Renaissance & Age of Discovery",
    start: 1500,
    end: 1600,
    icon: GiPalette,
    headline: "Exploration and Enlightenment",
  },
  {
    label: "Scientific Revolution",
    start: 1600,
    end: 1700,
    icon: GiCompass,
    headline: "Reason Reigns",
  },
  {
    label: "Enlightenment & Imperial Expansion",
    start: 1700,
    end: 1800,
    icon: GiQuillInk,
    headline: "Revolutions and Reason",
  },

  // Industrial → Modern
  {
    label: "Industrial Revolution",
    start: 1800,
    end: 1870,
    icon: GiFactory,
    headline: "Machines Transform Lives",
  },
  {
    label: "Age of Empire & Globalization",
    start: 1870,
    end: 1914,
    icon: GiPalmTree,
    headline: "The World Connects",
  },
  {
    label: "World War Era",
    start: 1914,
    end: 1945,
    icon: GiFallingBomb,
    headline: "Global Conflict Engulfs Nations",
  },
  {
    label: "Cold War",
    start: 1945,
    end: 1990,
    icon: GiSubmarineMissile,
    headline: "Ideologies Clash",
  },
  {
    label: "Information Age",
    start: 1990,
    end: 2025,
    icon: GiWireframeGlobe,
    headline: "Digital Revolution",
  },
];

export const EAST_ASIA_RANGES = [
  {
    label: "Lower Paleolithic East Asia",
    start: -300000,
    end: -100000,
    icon: GiCaveEntrance,
    headline: "Early Homo erectus and stone tools",
  },
  {
    label: "Middle Paleolithic East Asia",
    start: -100000,
    end: -25000,
    icon: GiCaveman,
    headline: "Hunter-gatherers and regional traditions",
  },
  {
    label: "Upper Paleolithic East Asia",
    start: -25000,
    end: -10000,
    icon: GiFootprint,
    headline: "Refined tools and early art",
  },
  {
    label: "Early Neolithic East Asia",
    start: -10000,
    end: -2000,
    icon: GiStoneAxe,
    headline: "Rise of farming and pottery",
  },
  {
    label: "Early Dynastic China",
    start: -2000,
    end: -220,
    icon: GiWheat,
    headline: "Shang and Zhou foundations",
  },
  {
    label: "Qin–Han Imperial China",
    start: -220,
    end: 220,
    icon: GiMountainRoad,
    headline: "Unification and imperial formation",
  },
  {
    label: "Age of Division",
    start: 220,
    end: 590,
    icon: GiFlame,
    headline: "Fragmented kingdoms and Buddhism",
  },
  {
    label: "Sui–Tang Golden Age",
    start: 590,
    end: 907,
    icon: GiLaurelCrown,
    headline: "Cosmopolitan empire and Silk Road",
  },
  {
    label: "Song Commercial Peak",
    start: 907,
    end: 1280,
    icon: GiWheat,
    headline: "Urbanisation and economic expansion",
  },
  {
    label: "Yuan Mongol Rule",
    start: 1280,
    end: 1368,
    icon: GiAxeSword,
    headline: "Mongol rule over China",
  },
  {
    label: "Ming–Qing Late Imperial China",
    start: 1368,
    end: 1912,
    icon: GiTempleGate,
    headline: "Gunpowder states and global trade",
  },
  {
    label: "Republican & Modern China",
    start: 1912,
    end: 2025,
    icon: GiQuillInk,
    headline: "Revolution, war, and reform",
  },
];

// ————————————————— Islamic World ————————————————— //
export const ISLAMIC_WORLD_RANGES = [
  {
    label: "Lower Paleolithic Near East",
    start: -300000,
    end: -100000,
    icon: GiCaveEntrance,
    headline: "Early humans in the Fertile Crescent",
  },
  {
    label: "Middle Paleolithic Near East",
    start: -100000,
    end: -25000,
    icon: GiCaveman,
    headline: "Neanderthals and early sapiens",
  },
  {
    label: "Upper Paleolithic Near East",
    start: -25000,
    end: -10000,
    icon: GiFootprint,
    headline: "Early symbolic culture and rituals",
  },
  {
    label: "Early Neolithic Near East",
    start: -10000,
    end: -3000,
    icon: GiStoneAxe,
    headline: "Villages and early farming",
  },
  {
    label: "Bronze Age Near East",
    start: -3000,
    end: -1200,
    icon: GiAnvil,
    headline: "City-states and early empires",
  },
  {
    label: "Iron Age Near East",
    start: -1200,
    end: -600,
    icon: GiAxeSword,
    headline: "Assyria and regional states",
  },
  {
    label: "Classical & Hellenistic Near East",
    start: -600,
    end: 600,
    icon: GiLaurelCrown,
    headline: "Greek, Roman, and late antique worlds",
  },
  {
    label: "Rise of Islam",
    start: 600,
    end: 750,
    icon: GiDiploma,
    headline: "Muhammad, Rashidun, and Umayyads",
  },
  {
    label: "Classical Abbasid Caliphate",
    start: 750,
    end: 945,
    icon: GiTempleGate,
    headline: "Islamic Golden Age",
  },
  {
    label: "Fragmentation & Regional Sultanates",
    start: 945,
    end: 1258,
    icon: GiCastle,
    headline: "Fatimids, Seljuks, and regional powers",
  },
  {
    label: "Post-Abbasid Fragmentation",
    start: 1258,
    end: 1500,
    icon: GiTempleGate,
    headline: "Mamluks, Timurids, and successor states",
  },
  {
    label: "Gunpowder Empires",
    start: 1500,
    end: 1800,
    icon: GiAxeSword,
    headline: "Ottomans, Safavids, and Mughals",
  },
  {
    label: "Colonial & Nationalist Era",
    start: 1800,
    end: 1918,
    icon: GiMountains,
    headline: "European pressure and reform",
  },
  {
    label: "Modern Middle East",
    start: 1918,
    end: 2025,
    icon: GiQuillInk,
    headline: "Nation-states and contemporary conflicts",
  },
];

// ——————————————————— Africa ——————————————————— //
export const WEST_AFRICA_RANGES = [
  {
    label: "Paleolithic Era",
    start: -300000,
    end: -10000,
    icon: GiCaveEntrance,
    headline: "Early human presence within broader African Paleolithic developments",
  },
  {
    label: "Early Holocene Transformations",
    start: -10000,
    end: -3000,
    icon: GiFootprint,
    headline: "Saharan green phase, foraging expansion, and early pastoralism",
  },
  {
    label: "Proto-West African Complex Societies",
    start: -3000,
    end: -500,
    icon: GiStoneAxe,
    headline: "Dhar Tichitt, early metallurgy, and emergent regional networks",
  },
  {
    label: "Iron Age West Africa & Nok Horizon",
    start: -500,
    end: 300,
    icon: GiAxeSword,
    headline: "Nok culture, early ironworking, and proto-urban developments",
  },
  {
    label: "Sahelian Kingdom Formation",
    start: 300,
    end: 1200,
    icon: GiTempleGate,
    headline: "Ghana Empire, early trans-Saharan trade, and state formation",
  },
  {
    label: "Mali Empire & Sahelian High Civilisation",
    start: 1200,
    end: 1450,
    icon: GiCastle,
    headline: "Mali Empire peak, Mansa Musa era, Islamic scholarship networks",
  },
  {
    label: "Songhai Expansion & Forest States",
    start: 1450,
    end: 1600,
    icon: GiCompass,
    headline: "Songhai Empire, Hausa states, and forest kingdom consolidation",
  },
  {
    label: "Atlantic Trade Transformation",
    start: 1600,
    end: 1800,
    icon: GiPalmTree,
    headline: "Atlantic slave trade and restructuring of coastal and inland states",
  },
  {
    label: "Colonial West Africa",
    start: 1800,
    end: 1960,
    icon: GiMountains,
    headline: "European colonisation and administrative restructuring",
  },
  {
    label: "Postcolonial West Africa",
    start: 1960,
    end: 2025,
    icon: GiQuillInk,
    headline: "Independence, nation-building, and regional modern states",
  },
];

export const SUB_SAHARAN_AFRICA_RANGES = [
  {
    label: "Paleolithic Sub-Saharan Africa",
    start: -300000,
    end: -10000,
    icon: GiCaveEntrance,
    headline: "Early Homo sapiens evolution and widespread hunter-gatherer societies",
  },
  {
    label: "Late Stone Age & Holocene Transition",
    start: -10000,
    end: -5000,
    icon: GiFootprint,
    headline: "Climatic change, diversification of foraging cultures, and early regional identities",
  },
  {
    label: "Pastoralism & Early Agriculture Emergence",
    start: -5000,
    end: -1500,
    icon: GiWheat,
    headline: "Cattle pastoralism, early farming systems, and ecological expansion",
  },
  {
    label: "Early Iron Age & Bantu Expansion",
    start: -1500,
    end: 500,
    icon: GiAxeSword,
    headline: "Spread of ironworking, Bantu migrations, and formation of early settlements",
  },
  {
    label: "Regional Kingdom Formation",
    start: 500,
    end: 1200,
    icon: GiTempleGate,
    headline: "Development of structured kingdoms in Great Lakes, Central, Southern, and Horn regions",
  },
  {
    label: "Classical African Civilisational States",
    start: 1200,
    end: 1500,
    icon: GiCastle,
    headline: "Great Zimbabwe peak, Ethiopian Solomonic consolidation, Swahili coastal city-states",
  },
  {
    label: "Early Modern African States & External Contact",
    start: 1500,
    end: 1800,
    icon: GiCompass,
    headline: "Indian Ocean trade expansion, Portuguese influence, inland state restructuring",
  },
  {
    label: "Colonial Sub-Saharan Africa",
    start: 1800,
    end: 1960,
    icon: GiMountains,
    headline: "Scramble for Africa, colonial administration, and resistance movements",
  },
  {
    label: "Postcolonial Sub-Saharan Africa",
    start: 1960,
    end: 2025,
    icon: GiQuillInk,
    headline: "Independence, nation-building, and contemporary political and economic development",
  },
];

export const AFRICA_NORTH_RANGES = [
  {
    label: "Lower Paleolithic North Africa",
    start: -300000,
    end: -100000,
    icon: GiCaveEntrance,
    headline: "Early human occupation across Sahara margins and Nile corridor",
  },
  {
    label: "Middle Paleolithic North Africa",
    start: -100000,
    end: -25000,
    icon: GiCaveman,
    headline: "Aterian cultures and early symbolic behaviour",
  },
  {
    label: "Upper Paleolithic North Africa",
    start: -25000,
    end: -10000,
    icon: GiFootprint,
    headline: "Late Stone Age adaptation and climatic extremes",
  },
  {
    label: "Neolithic Sahara & Early Pastoral North Africa",
    start: -10000,
    end: -3000,
    icon: GiWheat,
    headline: "Pastoralism, early farming, and Saharan transformation",
  },
  {
    label: "Early Dynastic Egypt",
    start: -3000,
    end: -2686,
    icon: GiLaurelCrown,
    headline: "Formation of unified Pharaonic state",
  },
  {
    label: "Old Kingdom Egypt",
    start: -2686,
    end: -2181,
    icon: GiTempleGate,
    headline: "Pyramid age and centralised Old Kingdom power",
  },
  {
    label: "First Intermediate Period",
    start: -2181,
    end: -2055,
    icon: GiFlame,
    headline: "Political fragmentation and regional rule",
  },
  {
    label: "Middle Kingdom Egypt",
    start: -2055,
    end: -1650,
    icon: GiTempleGate,
    headline: "Reunification and classical Egyptian state expansion",
  },
  {
    label: "Second Intermediate Period",
    start: -1650,
    end: -1550,
    icon: GiFlame,
    headline: "Hyksos rule and political fragmentation",
  },
  {
    label: "New Kingdom Egypt",
    start: -1550,
    end: -1070,
    icon: GiLaurelCrown,
    headline: "Imperial Egypt and Mediterranean dominance",
  },
  {
    label: "Late Period Egypt",
    start: -1070,
    end: -332,
    icon: GiTempleGate,
    headline: "Assyrian, Persian, and native dynastic resurgence",
  },

  {
    label: "Phoenician & Carthaginian North Africa",
    start: -1200,
    end: -146,
    icon: GiShipWheel,
    headline: "Phoenician colonies and Punic civilisation",
  },
  {
    label: "Roman Africa",
    start: -146,
    end: 395,
    icon: GiLaurelCrown,
    headline: "Roman provinces of Africa and Numidia",
  },
  {
    label: "Vandal Kingdom & Byzantine Africa",
    start: 395,
    end: 640,
    icon: GiCastle,
    headline: "Germanic rule and Eastern Roman reconquest",
  },
  {
    label: "Early Islamic Maghreb",
    start: 640,
    end: 909,
    icon: GiTempleGate,
    headline: "Umayyad conquest and early Islamic administration",
  },
  {
    label: "Fatimid & Regional Fragmentation",
    start: 909,
    end: 1050,
    icon: GiCrown,
    headline: "Fatimid Caliphate and emerging regional powers",
  },
  {
    label: "Almoravid & Almohad Empires",
    start: 1050,
    end: 1269,
    icon: GiCastle,
    headline: "Reformist Berber empires of the Maghreb",
  },
  {
    label: "Marinid, Hafsid & Zayyanid States",
    start: 1269,
    end: 1500,
    icon: GiTempleGate,
    headline: "Regional Maghreb dynasties and fragmentation",
  },
  {
    label: "Ottoman & Early Modern North Africa",
    start: 1500,
    end: 1800,
    icon: GiCompass,
    headline: "Ottoman provinces and semi-autonomous regencies",
  },
  {
    label: "Colonial North Africa",
    start: 1800,
    end: 1960,
    icon: GiMountains,
    headline: "French, British, Spanish, and Italian rule",
  },
  {
    label: "Modern North Africa",
    start: 1960,
    end: 2025,
    icon: GiQuillInk,
    headline: "Independence states and contemporary political order",
  },
];

// ————————————————— North America ————————————————— //
export const NORTH_AMERICAS_RANGES = [
  {
    label: "Pleistocene Era",
    start: -300000,
    end: -50000,
    icon: GiCaveEntrance,
    headline: "Possible early migrations and unconfirmed human presence debates",
  },
  {
    label: "Late Pleistocene Pre-Paleoindian Cultures",
    start: -50000,
    end: -20000,
    icon: GiFootprint,
    headline: "Early migration waves and Ice Age adaptation phases",
  },
  {
    label: "Paleoindian Traditions",
    start: -20000,
    end: -12000,
    icon: GiFootprint,
    headline: "First widely established human populations and megafauna hunting",
  },
  {
    label: "Late Paleoindian Transition",
    start: -12000,
    end: -8000,
    icon: GiAxeSword,
    headline: "Post-glacial adaptation and regionalisation begins",
  },

  {
    label: "Early Archaic Period",
    start: -8000,
    end: -5000,
    icon: GiAxeSword,
    headline: "Broad-spectrum foraging and ecological diversification",
  },
  {
    label: "Middle Archaic Period",
    start: -5000,
    end: -2000,
    icon: GiWheat,
    headline: "Technological refinement and regional cultural traditions",
  },
  {
    label: "Late Archaic Period",
    start: -2000,
    end: -1000,
    icon: GiStoneAxe,
    headline: "Sedentism increases and early proto-agricultural systems emerge",
  },

  {
    label: "Early Woodland Period",
    start: -1000,
    end: 200,
    icon: GiWheat,
    headline: "Pottery traditions, early agriculture, and mound-building origins",
  },
  {
    label: "Middle Woodland Interaction Era",
    start: 200,
    end: 600,
    icon: GiTempleGate,
    headline: "Long-distance exchange networks (Hopewell tradition peak)",
  },
  {
    label: "Late Woodland Regionalisation",
    start: 600,
    end: 1000,
    icon: GiCastle,
    headline: "Regional societies and intensified settlement patterns",
  },

  {
    label: "Emergent Mississippian Horizon",
    start: 1000,
    end: 1200,
    icon: GiCastle,
    headline: "Formation of complex chiefdoms and early urban centres",
  },
  {
    label: "Classic Mississippian Civilisation",
    start: 1200,
    end: 1450,
    icon: GiLaurelCrown,
    headline: "Urban polities like Cahokia and hierarchical mound societies",
  },
  {
    label: "Post-Mississippian / Protohistoric Transition",
    start: 1450,
    end: 1600,
    icon: GiAxeSword,
    headline: "Collapse and transformation prior to sustained European contact",
  },

  {
    label: "Early Colonial Contact Phase",
    start: 1600,
    end: 1700,
    icon: GiCompass,
    headline: "Initial sustained European-Native contact zones",
  },
  {
    label: "Colonial Competition Era",
    start: 1700,
    end: 1776,
    icon: GiMountains,
    headline: "French, Spanish, and British imperial rivalry",
  },
  {
    label: "Revolutionary & Early Republic",
    start: 1776,
    end: 1820,
    icon: GiDiploma,
    headline: "Independence movements and formation of new states",
  },
  {
    label: "Expansion & Antebellum Era",
    start: 1820,
    end: 1865,
    icon: GiPalmTree,
    headline: "Territorial expansion, industrial roots, and civil conflict",
  },
  {
    label: "Industrial & Reconstruction Era",
    start: 1865,
    end: 1914,
    icon: GiFactory,
    headline: "Industrialisation, migration, and post-civil war restructuring",
  },

  {
    label: "World Wars Era",
    start: 1914,
    end: 1945,
    icon: GiFallingBomb,
    headline: "Global conflicts and rise of industrial superpowers",
  },
  {
    label: "Cold War North America",
    start: 1945,
    end: 1991,
    icon: GiSubmarineMissile,
    headline: "Superpower rivalry and technological expansion",
  },
  {
    label: "Contemporary North America",
    start: 1991,
    end: 2025,
    icon: GiQuillInk,
    headline: "Globalisation, digital era, and geopolitical realignment",
  },
];

// ————————————————— Mesoamerica ————————————————— //
export const MESOAMERICA_RANGES = [
  {
    label: "Paleolithic Era",
    start: -300000,
    end: -20000,
    icon: GiCaveEntrance,
    headline: "No confirmed human presence",
  },

  {
    label: "Paleoindian Period",
    start: -20000,
    end: -8000,
    icon: GiFootprint,
    headline: "Early hunter-gatherers and migration",
  },
  {
    label: "Archaic Period",
    start: -8000,
    end: -2000,
    icon: GiAxeSword,
    headline: "Transition to agriculture and settled life",
  },
  {
    label: "Preclassic (Formative) Period",
    start: -2000,
    end: 250,
    icon: GiWheat,
    headline: "Olmec civilization and early cities",
  },
  {
    label: "Early Classic Period",
    start: 250,
    end: 600,
    icon: GiTempleGate,
    headline: "Rise of Teotihuacan and Maya cities",
  },
  {
    label: "Late Classic Period",
    start: 600,
    end: 900,
    icon: GiTempleGate,
    headline: "Peak and collapse of Classic Maya civilization",
  },
  {
    label: "Postclassic Period",
    start: 900,
    end: 1521,
    icon: GiCastle,
    headline: "Toltec and Aztec dominance",
  },
  {
    label: "Spanish Conquest & Early Colonial",
    start: 1521,
    end: 1700,
    icon: GiMountains,
    headline: "Collapse of indigenous empires and colonial rule",
  },
  {
    label: "Colonial Mesoamerica",
    start: 1700,
    end: 1821,
    icon: GiPalmTree,
    headline: "New Spain and colonial society",
  },
  {
    label: "Independent Mexico & Region",
    start: 1821,
    end: 1910,
    icon: GiDiploma,
    headline: "Nation-building and instability",
  },
  {
    label: "Modern Mesoamerica",
    start: 1910,
    end: 2025,
    icon: GiQuillInk,
    headline: "Revolution and modern states",
  },
];

// ————————————————— Andean Americas ————————————————— //
export const ANDEAN_AMERICAS_RANGES = [
  {
    label: "Paleolithic Era",
    start: -300000,
    end: -20000,
    icon: GiCaveEntrance,
    headline: "No confirmed human presence",
  },

  {
    label: "Paleoindian Period",
    start: -20000,
    end: -8000,
    icon: GiFootprint,
    headline: "Early coastal and highland settlement",
  },
  {
    label: "Archaic Period",
    start: -8000,
    end: -1800,
    icon: GiAxeSword,
    headline: "Fishing economies and early villages",
  },
  {
    label: "Initial Period",
    start: -1800,
    end: -900,
    icon: GiWheat,
    headline: "First monumental architecture and agriculture",
  },
  {
    label: "Early Horizon",
    start: -900,
    end: -200,
    icon: GiTempleGate,
    headline: "Chavín religious and cultural influence",
  },
  {
    label: "Early Intermediate Period",
    start: -200,
    end: 600,
    icon: GiTempleGate,
    headline: "Regional cultures like Moche and Nazca",
  },
  {
    label: "Middle Horizon",
    start: 600,
    end: 1000,
    icon: GiCastle,
    headline: "Wari and Tiwanaku expansion",
  },
  {
    label: "Late Intermediate Period",
    start: 1000,
    end: 1470,
    icon: GiCastle,
    headline: "Fragmented regional states",
  },
  {
    label: "Late Horizon (Inca Empire)",
    start: 1470,
    end: 1533,
    icon: GiAxeSword,
    headline: "Rapid imperial expansion of the Inca",
  },
  {
    label: "Colonial Andes",
    start: 1533,
    end: 1800,
    icon: GiMountains,
    headline: "Spanish conquest and viceroyalty",
  },
  {
    label: "Republican Era",
    start: 1800,
    end: 1900,
    icon: GiDiploma,
    headline: "Independence and early republics",
  },
  {
    label: "Modern Andean States",
    start: 1900,
    end: 2025,
    icon: GiQuillInk,
    headline: "Modern nations and development",
  },
];

// —————————————————— Oceania —————————————————— //
export const OCEANIA_RANGES = [
  {
    label: "Lower Paleolithic Sahul",
    start: -300000,
    end: -60000,
    icon: GiCaveEntrance,
    headline: "Early humans in Australia–New Guinea",
  },
  {
    label: "Middle Paleolithic Sahul",
    start: -60000,
    end: -20000,
    icon: GiCaveman,
    headline: "Coastal and inland foragers",
  },
  {
    label: "Upper Paleolithic Sahul",
    start: -20000,
    end: -1500,
    icon: GiFootprint,
    headline: "Refined tools, adaptation, and early cultural complexity",
  },
  {
    label: "Early Settlement & Navigation",
    start: -1500,
    end: 800,
    icon: GiCompass,
    headline: "First Pacific migrations and Lapita expansion",
  },
  {
    label: "Regional Chiefdoms & Exchange",
    start: 800,
    end: 1500,
    icon: GiTempleGate,
    headline: "Polynesian chiefdoms and inter-island networks",
  },
  {
    label: "European Contact & Colonization",
    start: 1500,
    end: 1950,
    icon: GiMountains,
    headline: "Encounters, colonies, and protectorates",
  },
  {
    label: "Modern Pacific States",
    start: 1950,
    end: 2025,
    icon: GiQuillInk,
    headline: "Self-determination and island nations",
  },
];

// ————————————————— South Asia ————————————————— //
export const SOUTH_ASIA_RANGES = [
  {
    label: "Lower Paleolithic South Asia",
    start: -300000,
    end: -60000,
    icon: GiCaveEntrance,
    headline: "Early hunter-gatherers using core-and-flake tools",
  },
  {
    label: "Middle Paleolithic South Asia",
    start: -60000,
    end: -25000,
    icon: GiCaveman,
    headline: "Mobile foragers adapting to varied landscapes",
  },
  {
    label: "Upper Paleolithic South Asia",
    start: -25000,
    end: -10000,
    icon: GiFootprint,
    headline: "Refined tools and early rock art",
  },
  {
    label: "South Asian Mesolithic and Neolithic",
    start: -10000,
    end: -2600,
    icon: GiWheat,
    headline: "Microliths, herding, farming, and early settlements",
  },
  {
    label: "Indus Valley Civilization",
    start: -2600,
    end: -1900,
    icon: GiScrollUnfurled,
    headline: "Urban river-valley civilization",
  },
  {
    label: "Vedic and Mahajanapada Period",
    start: -1900,
    end: -322,
    icon: GiGreekSphinx,
    headline: "Vedic traditions, new religions, and early states",
  },
  {
    label: "Mauryan and Early Imperial South Asia",
    start: -322,
    end: 320,
    icon: GiLaurelCrown,
    headline: "Maurya, Indo-Greek, Kushan, and post-Mauryan powers",
  },
  {
    label: "Classical and Regional Kingdoms",
    start: 320,
    end: 1200,
    icon: GiTempleGate,
    headline: "Gupta, Pallava, Chalukya, and regional powers",
  },
  {
    label: "Delhi Sultanate and Regional States",
    start: 1200,
    end: 1526,
    icon: GiAxeSword,
    headline: "Turko-Afghan sultanates and regional kingdoms",
  },
  {
    label: "Mughal and Early Modern South Asia",
    start: 1526,
    end: 1757,
    icon: GiCastle,
    headline: "Mughals, Deccan states, and expanding trade",
  },
  {
    label: "Colonial South Asia",
    start: 1757,
    end: 1947,
    icon: GiMountains,
    headline: "Company rule, the Raj, and anti-colonial movements",
  },
  {
    label: "Modern South Asia",
    start: 1947,
    end: 2025,
    icon: GiQuillInk,
    headline: "Partition, independence, and regional states",
  },
];

// ————————————————— Steppe ————————————————— //
export const STEPPE_RANGES = [
  {
    label: "Lower Paleolithic Steppe",
    start: -300000,
    end: -100000,
    icon: GiCaveEntrance,
    headline: "Early human hunters on the Eurasian grasslands",
  },
  {
    label: "Middle Paleolithic Steppe",
    start: -100000,
    end: -25000,
    icon: GiCaveman,
    headline: "Neanderthals and early sapiens across the steppes",
  },
  {
    label: "Upper Paleolithic Steppe",
    start: -25000,
    end: -10000,
    icon: GiFootprint,
    headline: "Hunter‑gatherers and symbolic culture",
  },
  {
    label: "Early Steppe Pastoralists",
    start: -10000,
    end: -1000,
    icon: GiWheat,
    headline: "Shepherds and herders before horse empires",
  },
  {
    label: "Early Nomadic Cultures",
    start: -1000,
    end: 200,
    icon: GiAxeSword,
    headline: "Pastoralists and early horse peoples",
  },
  {
    label: "Scythian & Steppe Confederations",
    start: 200,
    end: 1200,
    icon: GiCastle,
    headline: "Horse‑archers and steppes empires",
  },
  {
    label: "Mongol Empire & Successors",
    start: 1200,
    end: 1400,
    icon: GiAxeSword,
    headline: "Mongol superstate and fragmentation",
  },
  {
    label: "Post‑Mongol Khanates",
    start: 1400,
    end: 1700,
    icon: GiCastle,
    headline: "Timurid, khanates, and nomadic states",
  },
  {
    label: "Incorporation into Empires",
    start: 1700,
    end: 1900,
    icon: GiMountains,
    headline: "Russian and Qing expansion",
  },
  {
    label: "Modern Central Asia",
    start: 1900,
    end: 2025,
    icon: GiQuillInk,
    headline: "Republics and post‑Soviet states",
  },
];

// ————————————————— Europe ————————————————— //
export const EUROPE_RANGES = [
  {
    label: "Lower Paleolithic Europe",
    start: -300000,
    end: -100000,
    icon: GiCaveEntrance,
    headline: "First humans in Europe and cold‑climate hunters",
  },
  {
    label: "Middle Paleolithic Europe",
    start: -100000,
    end: -25000,
    icon: GiCaveman,
    headline: "Neanderthals and early sapiens survive the ice",
  },
  {
    label: "Upper Paleolithic Europe",
    start: -25000,
    end: -10000,
    icon: GiFootprint,
    headline: "Cave art and symbolic revolution",
  },
  {
    label: "Mesolithic Europe",
    start: -10000,
    end: -5000,
    icon: GiWheat,
    headline: "Hunter‑gatherers after the glaciers",
  },
  {
    label: "Early Neolithic Europe",
    start: -5000,
    end: -3000,
    icon: GiStoneAxe,
    headline: "Farmers enter Europe and build megaliths",
  },
  {
    label: "Bronze Age Europe",
    start: -3000,
    end: -800,
    icon: GiAnvil,
    headline: "Kingdoms, warriors, and early states",
  },
  {
    label: "Iron Age Europe",
    start: -800,
    end: 0,
    icon: GiAxeSword,
    headline: "Celts, Germans, and rising elites",
  },
  {
    label: "Classical Antiquity",
    start: 0,
    end: 500,
    icon: GiLaurelCrown,
    headline: "Rome, Athens, and the Mediterranean world",
  },
  {
    label: "Late Antiquity",
    start: 500,
    end: 750,
    icon: GiTempleGate,
    headline: "Transformation of the Roman world",
  },
  {
    label: "Early Middle Ages",
    start: 750,
    end: 1000,
    icon: GiVisoredHelm,
    headline: "Kings, bishops, and local kingdoms",
  },
  {
    label: "High Middle Ages",
    start: 1000,
    end: 1300,
    icon: GiCastle,
    headline: "Cathedrals, crusades, and feudal states",
  },
  {
    label: "Late Middle Ages",
    start: 1300,
    end: 1500,
    icon: GiFlame,
    headline: "Plague, war, and late feudal crises",
  },
  {
    label: "Renaissance & Early Modern",
    start: 1500,
    end: 1700,
    icon: GiPalette,
    headline: "Humanism, reformation, and global exploration",
  },
  {
    label: "Revolutionary & Napoleonic Era",
    start: 1700,
    end: 1815,
    icon: GiDiploma,
    headline: "Revolution, nationalism, and Napoleonic wars",
  },
  {
    label: "Industrial & Nationalism",
    start: 1815,
    end: 1914,
    icon: GiFactory,
    headline: "Factories, railways, and new nations",
  },
  {
    label: "World War Era",
    start: 1914,
    end: 1945,
    icon: GiFallingBomb,
    headline: "Trenches, total war, and fascism",
  },
  {
    label: "Postwar Europe",
    start: 1945,
    end: 1990,
    icon: GiSubmarineMissile,
    headline: "Reconstruction and Cold War divisions",
  },
  {
    label: "European Integration",
    start: 1990,
    end: 2025,
    icon: GiWireframeGlobe,
    headline: "EU, expansion, and contemporary crises",
  },
];

// ———————————————— Southeast Asia ———————————————— //
export const SOUTHEAST_ASIA_RANGES = [
  {
    label: "Lower Paleolithic Southeast Asia",
    start: -300000,
    end: -60000,
    icon: GiCaveEntrance,
    headline: "Early humans in the rainforests and coasts",
  },
  {
    label: "Middle Paleolithic Southeast Asia",
    start: -60000,
    end: -25000,
    icon: GiCaveman,
    headline: "Regional hunter-gatherer traditions",
  },
  {
    label: "Upper Paleolithic Southeast Asia",
    start: -25000,
    end: -10000,
    icon: GiFootprint,
    headline: "Advanced tools and early seafaring",
  },
  {
    label: "Neolithic Southeast Asia",
    start: -10000,
    end: -2000,
    icon: GiWheat,
    headline: "Rice agriculture and early village societies",
  },
  {
    label: "Bronze & Early Iron Age Southeast Asia",
    start: -2000,
    end: -500,
    icon: GiAnvil,
    headline: "Metallurgy, trade networks, and proto-states",
  },
  {
    label: "Early States and Indianized Polities",
    start: -500,
    end: 800,
    icon: GiTempleGate,
    headline: "Funan, Chenla, and early Indic influence",
  },
  {
    label: "Classical Kingdoms & Maritime Empires",
    start: 800,
    end: 1400,
    icon: GiCompass,
    headline: "Srivijaya, Khmer, Champa, and trade networks",
  },
  {
    label: "Late Classical & Islamic Transition",
    start: 1400,
    end: 1600,
    icon: GiCastle,
    headline: "Majapahit, Ayutthaya, and rise of Islamic sultanates",
  },
  {
    label: "Early European Contact",
    start: 1600,
    end: 1800,
    icon: GiPalmTree,
    headline: "Portuguese, Dutch, and regional trade competition",
  },
  {
    label: "Colonial Southeast Asia",
    start: 1800,
    end: 1945,
    icon: GiMountains,
    headline: "European imperial dominance and restructuring",
  },
  {
    label: "Modern Southeast Asia",
    start: 1945,
    end: 2025,
    icon: GiQuillInk,
    headline: "Decolonization and nation-states",
  },
];

export const ARCTIC_RANGES = [
  {
    label: "Lower Paleolithic Arctic",
    start: -300000,
    end: -60000,
    icon: GiCaveEntrance,
    headline: "Ice-age human presence at the northern margins",
  },
  {
    label: "Middle Paleolithic Arctic",
    start: -60000,
    end: -25000,
    icon: GiCaveman,
    headline: "Cold-adapted hunter-gatherers",
  },
  {
    label: "Upper Paleolithic Arctic",
    start: -25000,
    end: -10000,
    icon: GiFootprint,
    headline: "Late Ice Age survival and migration",
  },
  {
    label: "Paleo-Arctic Traditions",
    start: -10000,
    end: -500,
    icon: GiAxeSword,
    headline: "Early Arctic cultures and mobile foragers",
  },
  {
    label: "Dorset Culture",
    start: -500,
    end: 1000,
    icon: GiCompass,
    headline: "Pre-Inuit maritime Arctic societies",
  },
  {
    label: "Thule Expansion",
    start: 1000,
    end: 1600,
    icon: GiAxeSword,
    headline: "Inuit expansion and whale-hunting societies",
  },
  {
    label: "Early European Contact",
    start: 1600,
    end: 1900,
    icon: GiMountains,
    headline: "Trade, missions, and colonial encroachment",
  },
  {
    label: "Modern Arctic",
    start: 1900,
    end: 2025,
    icon: GiQuillInk,
    headline: "Indigenous rights and Arctic geopolitics",
  },
];

export const JAPAN_RANGES = [
  {
    label: "Prehistoric Japan",
    start: -300000,
    end: -30000,
    icon: GiCaveEntrance,
    headline: "Early human presence before confirmed archaeological cultures",
  },
  {
    label: "Japanese Paleolithic",
    start: -30000,
    end: -14000,
    icon: GiCaveman,
    headline: "First confirmed human activity and stone tools",
  },
  {
    label: "Jōmon Period",
    start: -14000,
    end: -300,
    icon: GiFootprint,
    headline: "Sedentary foragers and early pottery culture",
  },
  {
    label: "Yayoi Period",
    start: -300,
    end: 250,
    icon: GiWheat,
    headline: "Rice agriculture and early state formation",
  },
  {
    label: "Kofun Period",
    start: 250,
    end: 538,
    icon: GiStoneAxe,
    headline: "Tomb mounds and Yamato state emergence",
  },
  {
    label: "Asuka Period",
    start: 538,
    end: 710,
    icon: GiCompass,
    headline: "Buddhism and early centralisation",
  },
  {
    label: "Nara Period",
    start: 710,
    end: 794,
    icon: GiTempleGate,
    headline: "First permanent capital and ritsuryō state",
  },
  {
    label: "Heian Period",
    start: 794,
    end: 1185,
    icon: GiTempleGate,
    headline: "Court culture and aristocratic dominance",
  },
  {
    label: "Kamakura Period",
    start: 1185,
    end: 1333,
    icon: GiCastle,
    headline: "First shogunate and samurai rule",
  },
  {
    label: "Muromachi Period",
    start: 1333,
    end: 1573,
    icon: GiCastle,
    headline: "Ashikaga rule and regional conflict",
  },
  {
    label: "Azuchi–Momoyama Period",
    start: 1573,
    end: 1603,
    icon: GiAxeSword,
    headline: "Unification under Nobunaga and Hideyoshi",
  },
  {
    label: "Edo Period",
    start: 1603,
    end: 1868,
    icon: GiWheat,
    headline: "Tokugawa rule and relative isolation",
  },
  {
    label: "Meiji Period",
    start: 1868,
    end: 1912,
    icon: GiFactory,
    headline: "Industrialisation and modernisation",
  },
  {
    label: "Taishō Period",
    start: 1912,
    end: 1926,
    icon: GiDiploma,
    headline: "Democracy and political change",
  },
  {
    label: "Shōwa Period (Pre-1945)",
    start: 1926,
    end: 1945,
    icon: GiVisoredHelm,
    headline: "Militarism and expansion",
  },
  {
    label: "Shōwa Period (Postwar)",
    start: 1945,
    end: 1989,
    icon: GiSubmarineMissile,
    headline: "Reconstruction and economic growth",
  },
  {
    label: "Heisei & Reiwa Japan",
    start: 1989,
    end: 2025,
    icon: GiWireframeGlobe,
    headline: "Modern Japan in a globalised world",
  },
];

export const UK_RANGES = [
  {
    label: "Paleolithic Britain",
    start: -300000,
    end: -10000,
    icon: GiCaveEntrance,
    headline: "Early humans and Ice Age environments",
  },
  {
    label: "Mesolithic Britain",
    start: -10000,
    end: -4000,
    icon: GiWheat,
    headline: "Hunter-gatherers in post-glacial landscapes",
  },
  {
    label: "Neolithic Britain",
    start: -4000,
    end: -2500,
    icon: GiStoneAxe,
    headline: "Farming and monument building",
  },
  {
    label: "Bronze Age Britain",
    start: -2500,
    end: -800,
    icon: GiAnvil,
    headline: "Metalworking and emerging elites",
  },
  {
    label: "Iron Age Britain",
    start: -800,
    end: 43,
    icon: GiAxeSword,
    headline: "Celtic societies and tribal kingdoms",
  },
  {
    label: "Roman Britain",
    start: 43,
    end: 410,
    icon: GiLaurelCrown,
    headline: "Province of the Roman Empire",
  },
  {
    label: "Sub-Roman Britain",
    start: 410,
    end: 600,
    icon: GiTempleGate,
    headline: "Post-Roman fragmentation and transition",
  },
  {
    label: "Anglo-Saxon England",
    start: 600,
    end: 871,
    icon: GiTempleGate,
    headline: "Kingdoms and Christianisation",
  },
  {
    label: "Viking Age England",
    start: 871,
    end: 1066,
    icon: GiAxeSword,
    headline: "Danelaw and Norse influence",
  },
  {
    label: "Norman & Angevin England",
    start: 1066,
    end: 1215,
    icon: GiCastle,
    headline: "Feudal monarchy and consolidation",
  },
  {
    label: "High Medieval England",
    start: 1215,
    end: 1348,
    icon: GiCastle,
    headline: "Magna Carta and baronial power",
  },
  {
    label: "Late Medieval England",
    start: 1348,
    end: 1485,
    icon: GiFlame,
    headline: "Black Death and Wars of the Roses",
  },
  {
    label: "Tudor England",
    start: 1485,
    end: 1603,
    icon: GiPalette,
    headline: "Reformation and centralisation",
  },
  {
    label: "Stuart Britain",
    start: 1603,
    end: 1714,
    icon: GiAxeSword,
    headline: "Union, civil war, and constitutional change",
  },
  {
    label: "Georgian Britain",
    start: 1714,
    end: 1837,
    icon: GiFactory,
    headline: "Empire expansion and industrialisation",
  },
  {
    label: "Victorian Britain",
    start: 1837,
    end: 1901,
    icon: GiFactory,
    headline: "Industrial peak and global empire",
  },
  {
    label: "Edwardian Britain",
    start: 1901,
    end: 1914,
    icon: GiVisoredHelm,
    headline: "Pre-war society and tensions",
  },
  {
    label: "World War Era",
    start: 1914,
    end: 1945,
    icon: GiFallingBomb,
    headline: "Total war and imperial decline",
  },
  {
    label: "Postwar Britain",
    start: 1945,
    end: 1979,
    icon: GiSubmarineMissile,
    headline: "Welfare state and decolonisation",
  },
  {
    label: "Late Modern Britain",
    start: 1979,
    end: 2025,
    icon: GiWireframeGlobe,
    headline: "Neoliberalism, EU, and Brexit-era politics",
  },
];

export const IRAN_RANGES = [
  {
    label: "Paleolithic Iranian Plateau",
    start: -300000,
    end: -10000,
    icon: GiCaveEntrance,
    headline: "Early human habitation and hunter-gatherer networks",
  },
  {
    label: "Post-Ice Age Transformation",
    start: -10000,
    end: -7000,
    icon: GiFootprint,
    headline: "Environmental stabilisation and early regional adaptation",
  },
  {
    label: "Early Settlement & Proto-Agriculture",
    start: -7000,
    end: -4000,
    icon: GiStoneAxe,
    headline: "Village formation and early farming systems (e.g., Zagros regions)",
  },
  {
    label: "Proto-Urban Elamite & Plateau Cultures",
    start: -4000,
    end: -2000,
    icon: GiAnvil,
    headline: "Elam, early administrative systems, and regional complexity",
  },
  {
    label: "Bronze Age Iranian Interaction Sphere",
    start: -2000,
    end: -1200,
    icon: GiTempleGate,
    headline: "Interregional trade, Indo-Iranian movement, and Elamite continuity",
  },
  {
    label: "Late Bronze to Early Iron Transition",
    start: -1200,
    end: -800,
    icon: GiFallingBomb,
    headline: "Regional restructuring and emergence of Iranian-speaking groups",
  },
  {
    label: "Median Formation & Early Iranian States",
    start: -800,
    end: -550,
    icon: GiAxeSword,
    headline: "Median polity formation and consolidation of plateau societies",
  },
  {
    label: "Imperial Iranian Plateau Systems",
    start: -550,
    end: -330,
    icon: GiLaurelCrown,
    headline: "Achaemenid imperial integration across Afro-Eurasia",
  },
  {
    label: "Hellenistic & Regional Iranian Rule",
    start: -330,
    end: 224,
    icon: GiTempleGate,
    headline: "Seleucid influence and Parthian state formation",
  },
  {
    label: "Sasanian System",
    start: 224,
    end: 651,
    icon: GiCastle,
    headline: "Centralised imperial administration and Zoroastrian state culture",
  },
  {
    label: "Early Islamic Iranian Transformation",
    start: 651,
    end: 900,
    icon: GiCompass,
    headline: "Political transition and cultural continuity under new systems",
  },
  {
    label: "Iranian Regional Dynastic Age",
    start: 900,
    end: 1500,
    icon: GiTempleGate,
    headline: "Tahirids, Samanids, Seljuks, and Timurid cultural synthesis",
  },
  {
    label: "Early Modern Iranian States",
    start: 1500,
    end: 1800,
    icon: GiCastle,
    headline: "Safavid, Afsharid, and regional imperial competition",
  },
  {
    label: "Qajar & Imperial Pressure Era",
    start: 1800,
    end: 1925,
    icon: GiMountains,
    headline: "External imperial influence and internal reform pressures",
  },
  {
    label: "Modern Iran",
    start: 1925,
    end: 2025,
    icon: GiWireframeGlobe,
    headline: "State modernisation, revolution, and contemporary politics",
  },
];

export const MEDITERRANEAN_RANGES = [
  {
    label: "Paleolithic Mediterranean World",
    start: -300000,
    end: -10000,
    icon: GiCaveEntrance,
    headline: "Early human dispersal across Africa, Europe, and the Near East",
  },
  {
    label: "Post-Ice Age Mediterranean Transition",
    start: -10000,
    end: -7000,
    icon: GiFootprint,
    headline: "Climate stabilisation and coastal-adapted foraging societies",
  },
  {
    label: "Early Agricultural Mediterranean Networks",
    start: -7000,
    end: -4000,
    icon: GiStoneAxe,
    headline: "Farming spread and village-based societies across the basin",
  },
  {
    label: "Proto-Urban Mediterranean Systems",
    start: -4000,
    end: -2000,
    icon: GiAnvil,
    headline: "Early cities in Egypt, Levant, Anatolia, and Mesopotamian interface zones",
  },
  {
    label: "Bronze Age Interconnected States",
    start: -2000,
    end: -1200,
    icon: GiTempleGate,
    headline: "Palace economies, maritime trade, and diplomatic systems",
  },
  {
    label: "Late Bronze Age Collapse & Reorganisation",
    start: -1200,
    end: -900,
    icon: GiFallingBomb,
    headline: "Widespread systemic collapse and regional restructuring",
  },
  {
    label: "Iron Age Mediterranean Formation",
    start: -900,
    end: -500,
    icon: GiAxeSword,
    headline: "Phoenician expansion, Greek polities, Neo-Assyrian influence",
  },
  {
    label: "Classical Mediterranean System",
    start: -500,
    end: 300,
    icon: GiLaurelCrown,
    headline: "Persian, Greek, and Roman imperial integration",
  },
  {
    label: "Late Antique Transformation",
    start: 300,
    end: 700,
    icon: GiTempleGate,
    headline: "Religious transformation and imperial fragmentation",
  },
  {
    label: "Early Medieval Mediterranean Fragmentation",
    start: 700,
    end: 1000,
    icon: GiVisoredHelm,
    headline: "Byzantine, Islamic, and Latin regional systems",
  },
  {
    label: "High Medieval Mediterranean Trade System",
    start: 1000,
    end: 1300,
    icon: GiCastle,
    headline: "Maritime republics, crusader states, and Islamic polities",
  },
  {
    label: "Late Medieval Mediterranean Crisis",
    start: 1300,
    end: 1500,
    icon: GiFlame,
    headline: "Pandemics, war, and shifting trade dominance",
  },
  {
    label: "Early Global Mediterranean Integration",
    start: 1500,
    end: 1700,
    icon: GiCompass,
    headline: "Atlantic shift and Ottoman-Habsburg competition",
  },
  {
    label: "Imperial Mediterranean World",
    start: 1700,
    end: 1900,
    icon: GiQuillInk,
    headline: "Declining centrality and global imperial pressures",
  },
  {
    label: "Modern Mediterranean Region",
    start: 1900,
    end: 2025,
    icon: GiWireframeGlobe,
    headline: "Nation-states, decolonisation, and modern geopolitics",
  },
];